// <auto-generated />
using ECommerceMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceMVC.Migrations.StoreDb
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20200425183040_updatedimgURL")]
    partial class updatedimgURL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerceMVC.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Classic website",
                            Image = "https://imgur.com/ex7bvr4",
                            Name = "Classic",
                            Price = 150.00m,
                            SKU = "12jrj830"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Hipster website",
                            Image = "https://imgur.com/KckYFPo",
                            Name = "Hipster",
                            Price = 300.00m,
                            SKU = "8fw4s10"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Antique website",
                            Image = "https://imgur.com/rIRLFbX",
                            Name = "Antique",
                            Price = 180.00m,
                            SKU = "4nj38s10"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Comical website",
                            Image = "https://imgur.com/xf5nzhK",
                            Name = "Comic",
                            Price = 210.00m,
                            SKU = "7mj38s10"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Natural website",
                            Image = "https://imgur.com/1k8nogz",
                            Name = "Nature",
                            Price = 2000.00m,
                            SKU = "12j38s10"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Technical website",
                            Image = "https://imgur.com/q1OefoY",
                            Name = "Technical",
                            Price = 200.00m,
                            SKU = "8fg38s10"
                        },
                        new
                        {
                            ID = 7,
                            Description = "Greyscale website",
                            Image = "https://imgur.com/lJrL4Sr",
                            Name = "Greyscale",
                            Price = 75.00m,
                            SKU = "8fw8s10"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Cozy website",
                            Image = "https://imgur.com/ZesihIk",
                            Name = "Cozy",
                            Price = 240.00m,
                            SKU = "yv538s10"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Colorful website",
                            Image = "https://imgur.com/26bU5zY",
                            Name = "Colorful",
                            Price = 350.00m,
                            SKU = "83nd8fn3"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Modern website",
                            Image = "https://imgur.com/G6NxY8n",
                            Name = "Modern",
                            Price = 200.00m,
                            SKU = "8fj38s10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
