// <auto-generated />
using ECommerceMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceMVC.Migrations.StoreDb
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20200501071553_initialdb")]
    partial class initialdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerceMVC.Models.CartItems", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartsID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CartsID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerceMVC.Models.Carts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("ECommerceMVC.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "A no nonsense design tailored to businesses with decerning taste. The Classic theme will allow your business to focus on what is important and not waste time with unnecessary features.",
                            Image = "https://i.imgur.com/ex7bvr4.jpg",
                            Name = "Classic",
                            Price = 1500.00m,
                            SKU = "12jrj830"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Not your average design, be unique, be bold and carve your own path. The flexibility in this design will ensure no two are the same,so go ahead,and let your creativity show.",
                            Image = "https://i.imgur.com/KckYFPo.jpg",
                            Name = "Hipster",
                            Price = 3000.00m,
                            SKU = "8fw4s10"
                        },
                        new
                        {
                            ID = 3,
                            Description = "A classic design that is reminiscent of a by gone era. With a comprehensive and eloquently designed website, you will see an increase in positive user experiences, resulting in a better profit margin.",
                            Image = "https://i.imgur.com/rIRLFbX.jpg",
                            Name = "Antique",
                            Price = 1800.00m,
                            SKU = "4nj38s10"
                        },
                        new
                        {
                            ID = 4,
                            Description = "An exciting design for the hero in everyone. The comic design will allow the inner hero of your business to shine.Do not be fooled be the straightforward design, this layout packs a punch!",
                            Image = "https://i.imgur.com/xf5nzhK.jpg",
                            Name = "Comic",
                            Price = 2100.00m,
                            SKU = "7mj38s10"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Get away from the hustle and bustle and take a deep breath. With a design that will make even the most adventurous feel right at home, this design is for those who are not afraid to get dirty and enjoy the great outdoors.",
                            Image = "https://i.imgur.com/1k8nogz.jpg",
                            Name = "Nature",
                            Price = 2000.00m,
                            SKU = "12j38s10"
                        },
                        new
                        {
                            ID = 6,
                            Description = "A design focused on showcasing technical data to convey your designs and all you to keep productive. With its straight forward layout you can spend less time fixing your site and more time being creative and doing what your passionate about.",
                            Image = "https://i.imgur.com/q1OefoY.jpg",
                            Name = "Technical",
                            Price = 2000.00m,
                            SKU = "8fg38s10"
                        },
                        new
                        {
                            ID = 7,
                            Description = "An elegant and minimalistic design to punctuate the things that are most important.This designs beauty is in its simplicity, when you need to present your site in a straightforward way this is the design to use.",
                            Image = "https://i.imgur.com/lJrL4Sr.jpg",
                            Name = "Greyscale",
                            Price = 1750.00m,
                            SKU = "8fw8s10"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Like a warm fire, your favorite sweater or a home cooked meal, this design will make you feel right at home.So settle in and get cozy, this design will make you want to take it easy and spend some time to enjoy the simple things.",
                            Image = "https://i.imgur.com/ZesihIk.jpg",
                            Name = "Cozy",
                            Price = 1400.00m,
                            SKU = "yv538s10"
                        },
                        new
                        {
                            ID = 9,
                            Description = "with a well thought out design you are ensured to have a site that pops. Not afraid of a little color, go crazy with your palette and show the world how far a little color can go.",
                            Image = "https://i.imgur.com/26bU5zY.png",
                            Name = "Colorful",
                            Price = 1900.00m,
                            SKU = "83nd8fn3"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Website that thrives in modern society and its fast changes. This website is for end user with modern taste and elegant details.",
                            Image = "https://i.imgur.com/aHUKS0C.png",
                            Name = "Modern",
                            Price = 2000.00m,
                            SKU = "8fj38s10"
                        });
                });

            modelBuilder.Entity("ECommerceMVC.Models.CartItems", b =>
                {
                    b.HasOne("ECommerceMVC.Models.Carts", "Carts")
                        .WithMany()
                        .HasForeignKey("CartsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceMVC.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
