// <auto-generated />
using ECommerceMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceMVC.Migrations.StoreDb
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerceMVC.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "very modern dumpster fires",
                            Image = "",
                            Name = "modern",
                            Price = 200.00m,
                            SKU = "8fj38s10"
                        },
                        new
                        {
                            ID = 2,
                            Description = "very hipster dumpster fires",
                            Image = "",
                            Name = "hipster",
                            Price = 300.00m,
                            SKU = "8fw4s10"
                        },
                        new
                        {
                            ID = 3,
                            Description = "very antique dumpster fires",
                            Image = "",
                            Name = "antique",
                            Price = 180.00m,
                            SKU = "4nj38s10"
                        },
                        new
                        {
                            ID = 4,
                            Description = "very comical dumpster fires",
                            Image = "",
                            Name = "comic",
                            Price = 210.00m,
                            SKU = "7mj38s10"
                        },
                        new
                        {
                            ID = 5,
                            Description = "very natural dumpster fires",
                            Image = "",
                            Name = "nature",
                            Price = 2000.00m,
                            SKU = "12j38s10"
                        },
                        new
                        {
                            ID = 6,
                            Description = "very technical dumpster fires",
                            Image = "",
                            Name = "technical",
                            Price = 200.00m,
                            SKU = "8fg38s10"
                        },
                        new
                        {
                            ID = 7,
                            Description = "very drab dumpster fires",
                            Image = "",
                            Name = "greyscale",
                            Price = 75.00m,
                            SKU = "8fw8s10"
                        },
                        new
                        {
                            ID = 8,
                            Description = "very cozy dumpster fires",
                            Image = "",
                            Name = "cozy",
                            Price = 240.00m,
                            SKU = "yv538s10"
                        },
                        new
                        {
                            ID = 9,
                            Description = "very colorful dumpster fires",
                            Image = "",
                            Name = "colorful",
                            Price = 350.00m,
                            SKU = "83nd8fn3"
                        },
                        new
                        {
                            ID = 10,
                            Description = "very classic dumpster fires",
                            Image = "",
                            Name = "classic",
                            Price = 150.00m,
                            SKU = "12jrj830"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
